local H = dofile("tests/helpers/load_addon.lua")

describe("log", function()
    local mock, ns, Log

    before_each(function()
        mock = H.mockAdapter.new()
        ns = H.newNs(H.pureFiles(), { adapter = mock })
        Log = ns.Log
        ns.DB.Init(nil, nil, 0)
    end)

    describe("Debug", function()
        it("prints nothing while debug is off", function()
            Log.Debug("hidden", 1)
            assert.are.same({}, mock.printed)
        end)

        it("prints the arguments, space separated, when debug is on", function()
            Log.SetDebug(true)
            Log.Debug("scan", 12, true, nil)
            assert.are.same({ "[debug] scan 12 true nil" }, mock.printed)
        end)
    end)

    describe("WarnOnce", function()
        it("prints a key only the first time", function()
            assert.is_true(Log.WarnOnce("k", "careful"))
            assert.is_false(Log.WarnOnce("k", "careful"))
            assert.are.same({ "careful" }, mock.printed)
        end)

        it("treats different keys separately and defaults the text to the key", function()
            Log.WarnOnce("one")
            Log.WarnOnce("two", "second")
            assert.are.same({ "one", "second" }, mock.printed)
        end)
    end)

    describe("debug flag", function()
        it("toggles and persists in settings.debug", function()
            assert.is_false(Log.IsDebug())
            assert.is_true(Log.ToggleDebug())
            assert.is_true(ns.DB.GetSettings().debug)
            assert.is_true(Log.IsDebug())
            assert.is_false(Log.ToggleDebug())
            assert.is_false(ns.DB.GetSettings().debug)
        end)

        it("is off and cannot be set before the database exists", function()
            local bare = H.newNs({ "Locale/enUS.lua", "Core/Util.lua", "Core/Log.lua" }, { adapter = mock })
            assert.is_false(bare.Log.IsDebug())
            assert.is_false(bare.Log.SetDebug(true))
            assert.is_false(bare.Log.ToggleDebug())
            bare.Log.Debug("ignored")
            assert.are.same({}, mock.printed)
        end)
    end)
end)
